server:
  port: 8082
#profile
spring:
  profiles:
    active: test

  #JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  #springdevtools
  devtools:
    restart:
      enabled: true
#rabbitmq server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest



